USE [TIDB];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [TI].[XAMA_STAGE_UPDATE_LINE_REQUISITION] (
[STAGE_UPDATE_LINE_REQUISITION_ID] int NOT NULL,
[CLIENT] char(6) NULL,
[REQUISITION_ID] int NULL,
[REQITEM_ID] int NULL,
[REQITEM_STATUS] char(2) NULL,
[DATCHG] datetime NULL,
[DATCRE] datetime NULL,
[USERCHG] varchar(254) NULL,
[USERCRE] varchar(254) NULL,
CONSTRAINT [PK__XAMA_STA__E5CE21135F75A2B9]
PRIMARY KEY NONCLUSTERED ([STAGE_UPDATE_LINE_REQUISITION_ID] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY],
CONSTRAINT [FK__XAMA_STAG__CLIEN__615DEB2B]
FOREIGN KEY ([CLIENT])
REFERENCES [TI].[AMT_CLIENT] ( [CLIENT] )
)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO