/****** Object: Table [TI].[XAMA_INVESTMENT_PROJECT]   Script Date: 21/06/2016 16:20:40 ******/
USE [TIDB];
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TI].[XAMA_INVESTMENT_PROJECT]') AND type in (N'U'))
BEGIN
DROP TABLE [TIDB].[TI].[XAMA_INVESTMENT_PROJECT];
END
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[TI].[XAMA_INVESTMENT_PROJECT]') AND type in (N'U'))
BEGIN
CREATE TABLE [TI].[XAMA_INVESTMENT_PROJECT] (
[INVESTMENT_PROJECT_ID] int NOT NULL,
[CLIENT] char(6) COLLATE Latin1_General_CI_AS NULL,
[PROJECT_NO] varchar(254) COLLATE Latin1_General_CI_AS NULL,
[DATCRE] datetime NULL,
[DATCHG] datetime NULL,
[USERCRE] varchar(254) COLLATE Latin1_General_CI_AS NULL,
[USERCHG] varchar(254) COLLATE Latin1_General_CI_AS NULL,
[PROJECTDESCRIPTION] varchar(254) COLLATE Latin1_General_CI_AS NULL,
[STARTDATE] datetime NULL,
[FINISHDATE] datetime NULL,
CONSTRAINT [PK__XAMA_INV__3FB205D748923D61]
PRIMARY KEY CLUSTERED ([INVESTMENT_PROJECT_ID] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY],
CONSTRAINT [FK__XAMA_INVE__CLIEN__4A7A85D3]
FOREIGN KEY ([CLIENT])
REFERENCES [TI].[AMT_CLIENT] ( [CLIENT] )
)
ON [PRIMARY];
END;
GO

