/****** Object: Table [TI].[AMA_PERSON]   Script Date: 16/06/2016 16:59:00 ******/
USE [TIDB];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [TI].[AMA_PERSON] (
[PERSON_ID] int NOT NULL,
[CLIENT] char(6) NULL,
[PERS_NO] varchar(254) NULL,
[LASTNAME] varchar(254) NULL,
[FIRSTNAME] varchar(254) NULL,
[TITLE] varchar(254) NULL,
[CODE] varchar(16) NULL,
[PHONE_NO] varchar(254) NULL,
[FAX_NO] varchar(254) NULL,
[DEPARTMENT_ID] int NULL,
[SPECIALIST_AREA] varchar(254) NULL,
[LOCATION_ID] int NULL,
[COSTCENTER_ID] int NULL,
[PERS_USERID] varchar(254) NULL,
[VALIDFROM] datetime NULL,
[VALIDTO] datetime NULL,
[BUSINESSPART_ID] int NULL,
[SHORTTEXT] varchar(254) NULL,
[PERS_TYPE] varchar(254) NULL,
[CELL] varchar(254) NULL,
[PAGER] varchar(254) NULL,
[EMAIL] varchar(254) NULL,
[PERS_STATUS] varchar(254) NULL,
[MAILSTOP] varchar(254) NULL,
[PERS_INFO] varchar(254) NULL,
[S3USER_ID] int NULL,
[Z_CIVICO] varchar(254) NULL,
[Z_EDIFICIO] varchar(254) NULL,
[Z_PIANO] varchar(254) NULL,
[Z_PADIGLIONE] varchar(254) NULL,
[Z_STANZA] varchar(254) NULL,
[Z_RIF_TEL] varchar(254) NULL,
[PFLDC07] varchar(254) NULL,
[PFLDC08] varchar(254) NULL,
[PFLDC09] varchar(254) NULL,
[PFLDC10] varchar(254) NULL,
[Z_ULTIMO_IND] int NULL,
[Z_AREA_GESTITA] int NULL,
[Z_SOTTOAREA_GESTITA] int NULL,
[PFLDD04] numeric(15, 5) NULL,
[PFLDD05] numeric(15, 5) NULL,
[PFLDA01] datetime NULL,
[PFLDA02] datetime NULL,
[PFLDA03] datetime NULL,
[DATCRE] datetime NULL,
[DATCHG] datetime NULL,
[USERCRE] varchar(254) NULL,
[USERCHG] varchar(254) NULL,
[z_data_certif_RUN] datetime NULL,
[Z_AREA_ID] int NULL,
[LANGUAGE] varchar(40) NULL,
[EVALUATED_ID] int NULL,
[HLQ1] int NULL,
[HLQ2] int NULL,
[CTI_CELL] varchar(50) NULL,
[CTI_PHONE_NO] varchar(50) NULL,
[IF_UPDATE] char(1) NULL,
[PFLDC01] varchar(254) NULL,
[PFLDC02] varchar(254) NULL,
[PFLDC03] varchar(254) NULL,
[PFLDC04] varchar(254) NULL,
[PFLDC05] varchar(254) NULL,
[PFLDC06] varchar(254) NULL,
[PFLDD01] numeric(15, 5) NULL,
[PFLDD02] numeric(15, 5) NULL,
[PFLDD03] numeric(15, 5) NULL,
[POSITION] varchar(254) NULL,
[CELL_PRIV] varchar(254) NULL,
[EMAIL_PRIV] varchar(254) NULL,
[PHONE_NO_PRIV] varchar(254) NULL,
[FAX_NO_PRIV] varchar(254) NULL,
[SERVICEDOMAIN_ID] int NULL,
[LOCATION_ID1] int NULL,
[Z_EXTERNALCORPORATION_ID] int NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
