USE [TIDB];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [TI].[XAMA_INVESTMENT_PROJECT] (
[INVESTMENT_PROJECT_ID] int NOT NULL,
[CLIENT] char(6) NULL,
[PRIORITY] char(2) NULL,
[PROJECTDESCRIPTION] varchar(254) NULL,
[STARTDATE] datetime NULL,
[FINISHDATE] datetime NULL,
[DATCRE] datetime NULL,
[DATCHG] datetime NULL,
[USERCRE] varchar(254) NULL,
[USERCHG] varchar(254) NULL)