USE [TIDB];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [TI].[XAMA_STAGE_UPDATE_ASSET] (
[USERCRE] varchar(254) NULL,
[USERCHG] varchar(254) NULL,
[STAGE_UPDATE_ASSET_ID] int IDENTITY(1, 1) NOT NULL,
[SERIAL_NUMBER] varchar(254) NULL,
[FLG_IMPORT] char(1) NULL,
[DATCHG] datetime NULL,
[DATCRE] datetime NULL,
[COD_ERROR] varchar(254) NULL,
[CLIENT] char(6) NULL,
[RDA] varchar(254) NULL,
[SAC] varchar(254) NULL,
[IDENT] varchar(254) NULL,
CONSTRAINT [PK_XAMA_STAGE_UPDATE_ASSET]
PRIMARY KEY CLUSTERED ([STAGE_UPDATE_ASSET_ID] ASC)
WITH ( PAD_INDEX = OFF,
FILLFACTOR = 100,
IGNORE_DUP_KEY = OFF,
STATISTICS_NORECOMPUTE = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON,
DATA_COMPRESSION = NONE )
 ON [PRIMARY],
CONSTRAINT [FK_XAMA_STAGE_UPDATE_ASSET_AMT_CLIENT]
FOREIGN KEY ([CLIENT])
REFERENCES [TI].[AMT_CLIENT] ( [CLIENT] )
)
ON [PRIMARY];
GO
